### ISSUE TITLE
findEnumeratedCatalogEntry undefined issue

### ISSUE THREAD

**Issue by pavankumar88veeru** [ZEISS-PiWeb/PiWeb-Variable-Extension#2]
Getting undefined catalog entry for a properly assigned Measurement Value for a characteristics with Attribute type and the catalog definition.

for (let characteristic of piweb.data.getInspectionPlanCollection().getCharacteristics())
{
    for (let measurement of piweb.data.getMeasurementCollection()) {
       const value = measurement.findValueByEntity(characteristic);
	   if(value != null)
	   {
       	        const CharCatalog = configuration.findEnumeratedCatalogEntry( characteristic, value);
	   	piweb.logger.debug('CharCatalog: ' + CharCatalog?.key.toString());
	   }
    }
}

**Comment by Schnjan** [comment]
Can you provide a minimal *qdb* and *ptx* sample that contains the extension?

**Comment by Schnjan** [comment]
The issue will be fixed in PiWeb Servicepack 8.2.24, 8.4.19 and 8.6.2.
